// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6PtiE-LHN8i03N6TiPi7NdHNXTUm3Ma0',
    appId: '1:128338547880:web:919034f85732c1d2b95e9d',
    messagingSenderId: '128338547880',
    projectId: 'bacon-70636',
    authDomain: 'bacon-70636.firebaseapp.com',
    storageBucket: 'bacon-70636.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmmZ8LOIYkeA6wyu6YrJj4m5FZPhRvEH0',
    appId: '1:128338547880:android:d758dd2d2eb92533b95e9d',
    messagingSenderId: '128338547880',
    projectId: 'bacon-70636',
    storageBucket: 'bacon-70636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXCdsIlJ8tl6TgTBzoD1dwdWnTwj3t1jQ',
    appId: '1:128338547880:ios:835e5427332db0cbb95e9d',
    messagingSenderId: '128338547880',
    projectId: 'bacon-70636',
    storageBucket: 'bacon-70636.appspot.com',
    androidClientId: '128338547880-bdgihnc1ps4n5c5upksle359ufp5f08b.apps.googleusercontent.com',
    iosClientId: '128338547880-40pf756cceeru7uoj7pil8lnqa8j09l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bacon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXCdsIlJ8tl6TgTBzoD1dwdWnTwj3t1jQ',
    appId: '1:128338547880:ios:835e5427332db0cbb95e9d',
    messagingSenderId: '128338547880',
    projectId: 'bacon-70636',
    storageBucket: 'bacon-70636.appspot.com',
    androidClientId: '128338547880-bdgihnc1ps4n5c5upksle359ufp5f08b.apps.googleusercontent.com',
    iosClientId: '128338547880-40pf756cceeru7uoj7pil8lnqa8j09l3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bacon',
  );
}
